export const itemdata = [
    { name: 'Chicken Pickle', description: 'Spicy Hot Juicy.', price: 350, dprice: 200, discount: '20%', imageSrc: '/Chicken Pickle.jpeg' },
    { name: 'Chick', description: 'Spicy Hot Juicy.', price: 300, dprice: 200, discount: '20%', imageSrc: '/Motichoor Ladoo Recipe _ Motichur Laddu.jpeg' },
    { name: 'Chicken Dinner', description: 'Spicy Hot Juicy.', price: 450, dprice: 200, discount: '20%', imageSrc: '/next.svg' },
    { name: 'Chicken leg', description: 'Spicy Hot Juicy.', price: 1250, dprice: 200, discount: '20%', imageSrc: '/next.svg' },
    { name: 'Chicken Pickle', description: 'Spicy Hot Juicy.', price: 350, dprice: 200, discount: '20%', imageSrc: '/Chicken Pickle.jpeg' },
    { name: 'Chick', description: 'Spicy Hot Juicy.', price: 300, dprice: 200, discount: '20%', imageSrc: '/Motichoor Ladoo Recipe _ Motichur Laddu.jpeg' },
    { name: 'Chicken Dinner', description: 'Spicy Hot Juicy.', price: 450, dprice: 200, discount: '20%', imageSrc: '/next.svg' },
    { name: 'Chicken leg', description: 'Spicy Hot Juicy.', price: 1250, dprice: 200, discount: '20%', imageSrc: '/next.svg' },
    { name: 'Chicken Pickle', description: 'Spicy Hot Juicy.', price: 350, dprice: 200, discount: '20%', imageSrc: '/Chicken Pickle.jpeg' },
    { name: 'Chick', description: 'Spicy Hot Juicy.', price: 300, dprice: 200, discount: '20%', imageSrc: '/Motichoor Ladoo Recipe _ Motichur Laddu.jpeg' },
    { name: 'Chicken Dinner', description: 'Spicy Hot Juicy.', price: 450, dprice: 200, discount: '20%', imageSrc: '/next.svg' },
    { name: 'Chicken leg', description: 'Spicy Hot Juicy.', price: 1250, dprice: 200, discount: '20%', imageSrc: '/next.svg' },
    { name: 'Chicken Pickle', description: 'Spicy Hot Juicy.', price: 350, dprice: 200, discount: '20%', imageSrc: '/Chicken Pickle.jpeg' },
    { name: 'Chick', description: 'Spicy Hot Juicy.', price: 300, dprice: 200, discount: '20%', imageSrc: '/Motichoor Ladoo Recipe _ Motichur Laddu.jpeg' },
    { name: 'Chicken Dinner', description: 'Spicy Hot Juicy.', price: 450, dprice: 200, discount: '20%', imageSrc: '/next.svg' },
    { name: 'Chicken leg', description: 'Spicy Hot Juicy.', price: 1250, dprice: 200, discount: '20%', imageSrc: '/next.svg' },
    { name: 'Chicken Pickle', description: 'Spicy Hot Juicy.', price: 350, dprice: 200, discount: '20%', imageSrc: '/Chicken Pickle.jpeg' },
    { name: 'Chick', description: 'Spicy Hot Juicy.', price: 300, dprice: 200, discount: '20%', imageSrc: '/Motichoor Ladoo Recipe _ Motichur Laddu.jpeg' },
    { name: 'Chicken Dinner', description: 'Spicy Hot Juicy.', price: 450, dprice: 200, discount: '20%', imageSrc: '/next.svg' },
    { name: 'Chicken leg', description: 'Spicy Hot Juicy.', price: 1250, dprice: 200, discount: '20%', imageSrc: '/next.svg' },
]